services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    networks:
      - pulse_watch
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3000:3000
  valkey:
    image: valkey/valkey:latest
    volumes:
      - valkey-data:/data
    networks:
      - pulse_watch
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - pulse_watch
  recovery-worker:
    build:
      context: ./monitor
      dockerfile: ./docker/recovery.worker.Dockerfile
    env_file: ./monitor/.env
    networks:
      - pulse_watch
    depends_on:
      db:
        condition: service_healthy
      valkey:
        condition: service_started
      backend:
        condition: service_started

  scheduler:
    build:
      context: ./monitor
      dockerfile: ./docker/scheduler.Dockerfile
    env_file: ./monitor/.env
    networks:
      - pulse_watch
    depends_on:
      db:
        condition: service_healthy
      valkey:
        condition: service_started
      backend:
        condition: service_started
  normal-worker:
    build:
      context: ./monitor
      dockerfile: ./docker/normal.worker.Dockerfile
    env_file: ./monitor/.env
    networks:
      - pulse_watch
    depends_on:
      db:
        condition: service_healthy
      valkey:
        condition: service_started
      backend:
        condition: service_started
  outbox-worker:
    build:
      context: ./monitor
      dockerfile: ./docker/outbox.Dockerfile
    env_file: ./monitor/.env
    networks:
      - pulse_watch
    depends_on:
      db:
        condition: service_healthy
      valkey:
        condition: service_started
      backend:
        condition: service_started
volumes:
  valkey-data:
  db-data:

networks:
  pulse_watch:
