name: Monitor Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: build monitor
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "monitor/go.mod"
          cache: true
      - name: checkout monitor and test
        working-directory: monitor
        run: go test ./...
